#!/bin/sh

HTML2PDF_HOME=/opt/html2pdf

if [ "$1" = "" ] || [ "$2" = "" ]; then
    echo "Usage: $(basename ${0}) INPUT_HTML_DIR OUTPUT_PDF_FILE"
    exit 1
fi

node $HTML2PDF_HOME/html2pdf.js $1 $2

